baseURL = "https://fabianhee-website.pages.dev/"
languageCode = "en-us"
title = "Fabian Hee"
theme = "blowfish"

[taxonomies]
  category = "categories"
  tag = "tags"
  platform = "platforms" # Custom taxonomy for your games