baseURL = "https://fabianhee-website.pages.dev/"
languageCode = "en-us"
title = "Fabian Hee"
theme = "blowfish"

# Google Analytics tracking ID. Set to empty string to disable.
googleAnalytics = "G-PEJEP8VZ2M"

[taxonomies]
  category = "categories"
  tag = "tags"
  platform = "platforms" # Custom taxonomy for your games

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
